# NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")

# Trigger CD when CI executed successfully
resources:
  pipelines:
    - pipeline: eshoponweb-ci
      source: eshoponweb-ci
      trigger: true

variables:
  azureserviceconnection: 'azure subs'
  webappname: 'eshoponwebleads'

stages:
- stage: Deploy
  displayName: Deploy to Web App
  jobs:
  - job: Deploy
    pool:
      vmImage: windows-latest
    steps:
    # Download artifact produced by CI pipeline
    - download: eshoponweb-ci

    # Deploy application package to existing Azure Web App
    - task: AzureRmWebAppDeployment@4
      displayName: Deploy Website to Azure Web App
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '$(azureserviceconnection)'
        appType: 'webApp'
        WebAppName: '$(webappname)'
        package: '$(Pipeline.Workspace)/eshoponweb-ci/Website/**/Web.zip'
        AppSettings: "-UseOnlyInMemoryDatabase true -ASPNETCORE_ENVIRONMENT Development"

          
